### ISSUE TITLE
Use `get_channels_name` instead of fixing the DNA channel number

### ISSUE THREAD

**Issue by vianamp** [AllenCellModeling/mti_nma#9]
We may ask Jamie whether this is always true or not. Or maybe a better idea is to use `get_channel_names` to look for the DNA channel `H3342`. Then we can be sure we will always be looking at the correct channel. I am going to create an issue for this one.

_Originally posted by @vianamp in https://github.com/AllenCellModeling/mti_nma/pull/7/review_comment/create_

**Comment by jcass11** [comment]
Fixed in PR#11
